[supervisord]
nodaemon=true

[program:mysql]
command=/usr/sbin/mysqld --user=mysql --datadir=/var/lib/mysql --bind-address=0.0.0.0
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php]
command=/usr/bin/php -S 0.0.0.0:8080 -t /opt/demo/app/public
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
